spring.application.name=spd
server.port=${PORT:8081}

# View configuration
spring.mvc.view.prefix=/templates/
spring.mvc.view.suffix=.html
spring.thymeleaf.cache=false

# MongoDB Configuration (Secrets hidden using Environment Variables)
spring.data.mongodb.uri=${MONGO_URI}
spring.data.mongodb.database=spd_library_mongo
